source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'active_link_to'
gem 'active_model_serializers'
gem 'activerecord-import'
gem 'acts-as-taggable-on', '~> 6.0'
gem 'ancestry'
gem 'api-pagination'
gem 'beta_code'
gem 'bootstrap4-kaminari-views'
gem 'bootstrap', '~> 4.3.1'
gem 'clockwork'
gem 'coffee-rails', '~> 4.2'
gem 'compass-rails'
gem 'consul'
gem 'datagrid'
gem 'devise'
gem 'devise-bootstrap-views'
gem 'i18n'
gem 'devise-i18n'
gem 'enum_help'
gem 'faraday'
gem 'faraday-http-cache'
gem 'faraday_middleware'
gem 'font-awesome-sass'
gem 'hamlit-rails'
gem 'it'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'jstree-rails-4'
gem 'jwt'
gem 'kaminari'
gem 'modularity'
gem 'multi_json'
gem 'naturalsort'
gem 'oauth2c'
gem 'octokit', '~> 4.0'
gem 'oj'
gem 'omniauth'
gem 'org-ruby'
gem 'page_title_helper'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.7'
gem 'rack-attack'
gem 'rack-cors'
gem 'rails', '~> 5.2.1.1'
gem 'rails-vue-loader'
gem 'rails_compatible_cookies_utils'
gem 'ransack'
gem 'redis-objects'
gem 'redis-rails'
gem 'resque'
gem 'resque-pool'
gem 'resque-web', require: 'resque_web'
gem 'rest-client'
gem 'rollbar'
gem 'roda'
gem 'rswag'
gem 'sass-rails', '~> 5.0'
gem 'simple_form'
gem 'shrine'
gem 'turbolinks', '~> 5'
gem 'toastr-rails'
gem 'typhoeus'
gem 'uglifier', '>= 1.3.0'
gem 'validate_url'
gem 'vuejs-rails'
gem 'webpacker'
gem 'libxml-ruby'

group :development, :test do
  gem 'awesome_rails_console'
  gem 'byebug', platforms: %i{mri mingw x64_mingw}
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'faker', require: false
  gem 'haml_lint', require: false
  gem 'reek'
  gem 'rspec-rails', '~> 3.5'
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
  gem 'selenium-webdriver'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'simplecov'
  gem 'webmock'
end

group :development do
  gem 'annotate'
  gem 'letter_opener'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'pry-rails'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'

  gem 'awesome_print', require: 'ap'
end
